---
# file: oracle-java/defaults/main.yml
#
# defaults file
#
jdk_mirrors: http://localhost:8081/nexus/content/repositories/thirdparty/java/jdk

oracle_java_dir_source: '/usr/local/src'

oracle_java_set_as_default: no

oracle_java_version: 7
oracle_java_version_update: 71
oracle_java_version_build: 14
oracle_java_version_string: "1.{{ oracle_java_version }}.0_{{ oracle_java_version_update }}"
